load(":define_modules.bzl", "define_modules")

define_modules("sdxkova", "perf")
define_modules("sdxkova", "debug")

define_modules("sdxkova.cpe.wkk", "perf")
define_modules("sdxkova.cpe.wkk", "debug")

define_modules("sdxkova.512", "perf")
define_modules("sdxkova.512", "debug")

package(
    default_visibility = [
        "//visibility:public",
    ],
)
