#!/bin/sh /etc/rc.common
#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=95
STOP=93

USE_PROCD=1
PROCD_DEBUG=1

start_service() {
	chown root:thermal /sys/class/net/eth1/suspend_ipa_offload
	chmod 0664 /sys/class/net/eth1/suspend_ipa_offload
	chown root:thermal /sys/class/net/eth1/thermal_netlink
	chmod 0664 /sys/class/net/eth1/thermal_netlink
	chown root:thermal /sys/class/net/eth1/change_if
	chmod 0664 /sys/class/net/eth1/change_if
	procd_open_instance
	procd_set_param command /usr/bin/thermal-eth-netlink
	procd_set_param user thermal
	procd_set_param group thermal
	procd_close_instance
}

stop_service() {
	echo "Stopping thermal-eth-netlink Instance"
}
