#!/bin/sh /etc/rc.common

#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear.

IPACM_DEBUG=0

START=11
STOP=88

USE_PROCD=1
PROCD_DEBUG=1

IPACM_PID_FILE=/var/run/data/ipa/ipacm.pid

start_service() {
	mkdir -p /var/run/data/ipa
	chmod 755 /var/run/data/ipa
	chown radio:radio /var/run/data/ipa

	mkdir -p /var/run/data/monitor
	chmod 755 /var/run/data/monitor
	chown radio:radio /var/run/data/monitor

	mkdir -p /dev/socket/data/ipa
	chmod 755 /dev/socket/data/ipa
	chown radio:radio /dev/socket/data/ipa

	mkdir -p /tmp/data_ipa
	chmod 755 /tmp/data_ipa
	chown radio:radio /tmp/data_ipa

	mkdir -p /data/misc/ipa
	chmod 755 /data/misc/ipa
	chown radio:radio /data/misc/ipa

	chmod -R 777 /etc/data/ipa
	chown -R radio:root /etc/data/ipa
	mkdir -p /data/data_ipa
	chmod 755 /data/data_ipa
	chown radio:radio /data/data_ipa

	chmod +x /data/ipa_script.sh
	chown radio:radio /data/ipa_script.sh

	procd_open_instance
	if [ $IPACM_DEBUG = 1 ]; then
		rm -f /data/data_ipa/ipacm_log.txt
		procd_set_param command /bin/sh -c "/usr/bin/ipacm >> /data/data_ipa/ipacm_log.txt"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param nice "-1"
	else
		procd_set_param command /usr/bin/ipacm
		procd_set_param nice "-1"
	fi
	[ -x /sbin/ujail -a -e /etc/capabilities/ipacm.json ] && {
		procd_add_jail ipacm
		procd_set_param capabilities /etc/capabilities/ipacm.json
		procd_set_param user radio
		procd_set_param group radio
	}
	procd_set_param limits core="unlimited"
	procd_set_param respawn 5 10 60
	procd_close_instance
}

stop_service() {
	echo "Stopping ipacm Instance"
	service_stop /usr/bin/ipacm && rm $IPACM_PID_FILE
}
