#!/bin/sh /etc/rc.common

#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear.

START=19
STOP=74

USE_PROCD=1
PROCD_DEBUG=1

IPACM_PID_FILE=/var/run/data/ipa/ipacm.pid

start_service() {
		mkdir -p 755 /var/run/data/ipa
		chown radio:radio /var/run/data/ipa

		mkdir -p 755 /dev/socket/data/ipa
		chown radio:radio /dev/socket/data/ipa

		mkdir -p 755 /tmp/data_ipa
		chown radio:radio /tmp/data_ipa

		mkdir -p 755 /data/misc/ipa
		chown radio:radio /data/misc/ipa

		chown -R radio:root /etc/data/ipa
		chmod -R 777 /etc/data/ipa

		chmod 666 /dev/wwan_ioctl
		chmod 666 /dev/ipa
		chmod 660 /dev/ipaNatTable
		chmod 666 /dev/ipa_adpl
		chmod 666 /dev/ipa_odl_ctl
                chmod 660 /dev/ipaIpv6CTTable

		chown -h radio:radio /dev/wwan_ioctl
		chown -h radio:radio /dev/ipa
		chown -h radio:radio /dev/ipaNatTable
		chown -h radio:radio /dev/ipa_adpl
		chown -h radio:radio /dev/ipa_odl_ctl
                chown -h radio:radio /dev/ipaIpv6CTTable

		procd_open_instance
		procd_set_param command /usr/bin/ipacm
		[ -x /sbin/ujail -a -e /etc/capabilities/ipacm.json ] && {
			procd_add_jail ipacm
			procd_set_param capabilities /etc/capabilities/ipacm.json
			procd_set_param user radio
			procd_set_param group radio
		}
                procd_set_param limits core="unlimited"
		procd_close_instance
}

stop_service() {
		echo "Stopping ipacm Instance"
                service_stop /usr/bin/ipacm && rm $IPACM_PID_FILE
}
