#!/bin/sh /etc/rc.common

#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear.

START=70
STOP=74

USE_PROCD=1
PROCD_DEBUG=1

IPACM_PID_FILE=/var/run/data/ipa/ipacm.pid

start_service() {
	        mkdir -p /var/run/data/ipa
                mkdir -p /dev/socket/data/ipa
                mkdir -p /tmp/data
                mkdir -p /data/misc/ipa
		procd_open_instance
		procd_set_param command /usr/bin/ipacm
		procd_close_instance
}

stop_service() {
		echo "Stopping ipacm Instance"
                service_stop /usr/bin/ipacm && rm $IPACM_PID_FILE
}
