From 3e887d7143d71fc5ed9f4ba5c523acf51bb60924 Mon Sep 17 00:00:00 2001
From: Paras Singh Jain<parassin@codeaurora.org>
Date: Fri, 20 Nov 2020 15:30:13 +0530
Subject: [PATCH] New
signed-off: Paras Singh Jain<parassin@codeaurora.org>

---
 Makefile | 27 ++++++++++++---------------
 1 file changed, 12 insertions(+), 15 deletions(-)

diff --git a/Makefile b/Makefile
index 95651b6..2d0442e 100644
--- a/Makefile
+++ b/Makefile
@@ -5,21 +5,21 @@ PROGRELEASE:=4
 PROGVERSION_:=2.0.10
 PROGVERSION:=$(PROGVERSION_)-$(PROGRELEASE)
 PROGDATE:=December\ 2011
-LOCKFILE?=/var/lib/ebtables/lock
+LOCKFILE?=${localstatedir}lib/ebtables/lock
 LOCKDIR:=$(shell echo $(LOCKFILE) | sed 's/\(.*\)\/.*/\1/')/
 
 # default paths
-LIBDIR:=/usr/lib
-MANDIR:=/usr/local/man
-BINDIR:=/usr/local/sbin
-ETCDIR:=/etc
-INITDIR:=/etc/rc.d/init.d
-SYSCONFIGDIR:=/etc/sysconfig
+LIBDIR:=${libdir}
+MANDIR:=${mandir}
+BINDIR:=${sbindir}
+ETCDIR:=${sysconfdir}
+INITDIR:=${ETCDIR}/rc.d/init.d
+SYSCONFIGDIR:=${ETCDIR}/ebtables
 DESTDIR:=
 
 CFLAGS:=-Wall -Wunused -Werror
 CFLAGS_SH_LIB:=-fPIC -O3
-CC:=gcc
+CC:=${CC}
 
 ifeq ($(shell uname -m),sparc64)
 CFLAGS+=-DEBT_MIN_ALIGN=8 -DKERNEL_64_USERSPACE_32
@@ -32,7 +32,7 @@ useful_functions.o ebtables.o
 
 OBJECTS:=$(OBJECTS2) $(EXT_OBJS) $(EXT_LIBS)
 
-KERNEL_INCLUDES?=include/
+KERNEL_INCLUDES?=${STAGING_KERNEL_DIR}/source/include
 
 ETHERTYPESPATH?=$(ETCDIR)
 ETHERTYPESFILE:=$(ETHERTYPESPATH)/ethertypes
@@ -90,8 +90,7 @@ libebtc.so: $(OBJECTS2)
 	$(CC) -shared $(LDFLAGS) -Wl,-soname,libebtc.so -o libebtc.so -lc $(OBJECTS2)
 
 ebtables: $(OBJECTS) ebtables-standalone.o libebtc.so
-	$(CC) $(CFLAGS) $(CFLAGS_SH_LIB) $(LDFLAGS) -o $@ ebtables-standalone.o -I$(KERNEL_INCLUDES) -L. -Lextensions -Wl,--no-as-needed $(EXT_LIBSI) -lebtc \
-	-Wl,-rpath,$(LIBDIR)
+	$(CC) $(CFLAGS) $(CFLAGS_SH_LIB) $(LDFLAGS) -o $@ ebtables-standalone.o -I$(KERNEL_INCLUDES) -L. -Lextensions -Wl,--no-as-needed $(EXT_LIBSI) -lebtc
 
 ebtablesu: ebtablesu.c
 	$(CC) $(CFLAGS) $(PROGSPECSD) $< -o $@
@@ -100,15 +99,13 @@ ebtablesd.o: ebtablesd.c include/ebtables_u.h
 	$(CC) $(CFLAGS) $(PROGSPECSD) -c $< -o $@  -I$(KERNEL_INCLUDES)
 
 ebtablesd: $(OBJECTS) ebtablesd.o libebtc.so
-	$(CC) $(CFLAGS) -o $@ ebtablesd.o -I$(KERNEL_INCLUDES) -L. -Lextensions -lebtc $(EXT_LIBSI) \
-	-Wl,-rpath,$(LIBDIR)
+	$(CC) $(CFLAGS) -o $@ ebtablesd.o -I$(KERNEL_INCLUDES) -L. -Lextensions -Wl,--no-as-needed $(EXT_LIBSI) -lebtc
 
 ebtables-restore.o: ebtables-restore.c include/ebtables_u.h
 	$(CC) $(CFLAGS) $(PROGSPECS) -c $< -o $@  -I$(KERNEL_INCLUDES)
 
 ebtables-restore: $(OBJECTS) ebtables-restore.o libebtc.so
-	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ ebtables-restore.o -I$(KERNEL_INCLUDES) -L. -Lextensions -lebtc $(EXT_LIBSI) \
-	-Wl,-rpath,$(LIBDIR)
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ ebtables-restore.o -I$(KERNEL_INCLUDES) -L. -Lextensions -Wl,--no-as-needed $(EXT_LIBSI) -lebtc
 
 .PHONY: daemon
 daemon: ebtablesd ebtablesu
-- 
2.25.0
