#!/bin/sh /etc/rc.common

#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=10
STOP=50

start() {
	/usr/bin/start_r8125_modules start

	if [[ $(cat /sys/class/net/eth0/device/device) == "0x8125" ]]; then
		echo "eth0 brought up by r8125"
		ethtool -s eth0 wol pg
		ethtool -K eth0 rxvlan off
	else
		echo "eth0 is not up by r8125"
	fi
}

stop() {
	echo "Stopping r8125 Instance"
}
