# Create directory in /var/run for location with required permissions
d /run/data/ipa 0755 radio radio - -
d /dev/socket/data/ipa 0755 radio radio - -
d /run/data/monitor 0755 radio radio - -
z /dev/ipaNatTable 0660 radio radio - -
z /dev/ipaIpv6CTTable 0660 radio radio - -
z /dev/ipa 0660 radio radio - -
z /dev/wwan_ioctl 0660 radio radio - -
