#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

ctrl_interface=/var/run/wpa_supplicant

eapol_version=3
ap_scan=0
fast_reauth=1

network={
	key_mgmt=NONE
	eapol_flags=0

	macsec_policy=1
#	macsec_integ_only=1

#	Following PSK are used only for testing purposes
	mka_cak=f1367df92a453a6d575cbd114849c514
	mka_ckn=61b1e91243798e7bb9d1ba25a0eea38eee7ad33ec924beb5d2932daf80668058

#	AQC HW has a bug that prevents us from disabling replay protection. As a
#	workaround, enable replay protection with the largest possible window size.
	macsec_replay_protect=1
	macsec_replay_window=4294967295
}

# vim: syntax=dosini
