#!/bin/sh /etc/rc.common

#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=76
STOP=70

USE_PROCD=1
PROCD_DEBUG=1
KER_VER="$(uname -r )"

start_service() {
		procd_open_instance
		procd_set_param command insmod /lib/modules/$KER_VER/kernel/techpack/data-eth/drivers/qps615/src/qps615.ko
		procd_close_instance
}

stop_service() {
		echo "Stopping qps615 Instance"
}
