#!/bin/sh /etc/rc.common

#Copyright (c) 2022-2024 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear


START=03
STOP=96

start() {
	/etc/initscripts/start_dataipa_le start

	chmod 666 /dev/wwan_ioctl
	chmod 666 /dev/ipa
	chmod 660 /dev/ipaNatTable
	chmod 666 /dev/ipa_adpl
	chmod 666 /dev/ipa_odl_ctl
	chmod 660 /dev/ipaIpv6CTTable

	chown -h radio:radio /dev/wwan_ioctl
	chown -h radio:radio /dev/ipa
	chown -h radio:radio /dev/ipaNatTable
	chown -h radio:radio /dev/ipa_adpl
	chown -h radio:radio /dev/ipa_odl_ctl
	chown -h radio:radio /dev/ipaIpv6CTTable
}

stop() {
	echo "Stopping dataipa Instance"
}
