#VLAN configurations
use_vlan_eth_emac_config=no
use_vlan_eth0_config=no
use_vlan_eth1_config=no
use_vlan_rndis_config=no
use_vlan_ecm_config=no
use_vlan_mhi_eth_config=no

#MHI config
use_mhi_config=no
use_mhi_eth_config=no

#Qos config
use_eth_qos_config=no

#TSN config
use_tsn_config=no

#ezmesh config
use_ezmesh_config=no

#RDKB config
use_rdkb_config=no

#Ipsec config
use_ipsec_config=no

#IPv6 NAT config
use_ipv6_nat_config=no

#stats config
ipa_disable_per_flow_stats=no
max_ipv4_stats_accel_conn=1000
max_ipv6_stats_accel_conn=1000

#dtsi fields config
ipa_wdi3_2g_holb_timeout=15
ipa_wdi3_5g_holb_timeout=31
tx_wrapper_cache_max_size=400
ipa_wan_skb_page=yes
filter_start_id=768
wan_rx_ring_size=224
lan_rx_ring_size=192
ipa_gen_rx_cmn_page_pool_sz_factor=5
ipa_gen_rx_cmn_temp_pool_sz_factor=3
