#VLAN configurations
use_vlan_eth_emac_config=no
use_vlan_eth0_config=no
use_vlan_eth1_config=no
use_vlan_rndis_config=no
use_vlan_ecm_config=no
use_vlan_mhi_eth_config=no

#MHI config
use_mhi_config=no
use_mhi_eth_config=no

#Qos config
use_eth_qos_config=no

#TSN config
use_tsn_config=no

#ezmesh config
use_ezmesh_config=no

#RDKB config
use_rdkb_config=no

#Ipsec config
use_ipsec_config=no