#! /bin/sh
# Copyright (c) 2019, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#Changes from Qualcomm Innovation Center are provided under the following license:
#Copyright (c) 2022, 2025 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/lib/modules/`uname -r`/
set -e

if [ -f /etc/os-release ]; then
        name=$(cat /etc/os-release | grep ^NAME | cut -d'"' -f2)
        if [ -n "$name" ] && [ $name = "prplOS" ]; then
                PRPL_WRT=1
        fi
fi

if [ -n "$PRPL_WRT" ]; then
    IPACONF=/etc/data/ipa_config.txt

    if [ -f $IPACONF ]; then
            echo "Updating device config and IPACONF contents to /dev/ipa" > /dev/kmsg
            cfg=$(cat $IPACONF)
            cfg=\""rdkb $cfg"\"
    else
            echo "Updating device config to /dev/ipa" > /dev/kmsg
            cfg=\""rdkb\""
    fi
fi

case "$1" in
  start)
        echo -n "Starting/Loading ipa module: "

        echo "ipa:start/load" > /dev/kmsg
        insmod /lib/modules/ipa/gsim.ko
        if [ -n "$PRPL_WRT" ]; then
            insmod /lib/modules/ipa/ipam.ko ipa_cfg=$cfg
        else
            insmod /lib/modules/ipa/ipam.ko
        fi
        insmod /lib/modules/ipa/ipanetm.ko
        insmod /lib/modules/ipa/rndisipam.ko
        insmod /lib/modules/ipa/ecmipam.ko
        insmod /lib/modules/ipa/ipa_clientsm.ko
        echo "done loading ipa module"
        ;;
  stop)
        echo -n "Bypassing Unloading of  ipa modules "
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
