#!/bin/bash
# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

set -e

# Use this as error code for incomplete commands
EINVAL=22

add_tc () {
	if [[ $# -lt 5 ]];
	then
		print_usage
		return $EINVAL
	fi

	local dev="$1"
	shift
	local dir="$1"
	shift
	local tc="$1"
	shift

	local action=""
	local smac=""
	local dmac=""
	local vlan=""
	local pcp=""
	local src=""
	local dst=""
	local bw=""

	while [[ $# -gt 0 ]]; do
		case "$1" in
			"--action")
				shift
				action="$1"
				shift
				;;
			"--smac")
				shift
				while [[ $# -gt 0 && "$1" != "--"* ]]; do
					smac+=" $1"
					shift
				done
				;;
			"--dmac")
				shift
				while [[ $# -gt 0 && "$1" != "--"* ]]; do
					dmac+=" $1"
					shift
				done
				;;
			"--vlan")
				shift
				while [[ $# -gt 0 && "$1" != "--"* ]]; do
					vlan+=" $1"
					shift
				done
				;;
			"--pcp")
				shift
				while [[ $# -gt 0 && "$1" != "--"* ]]; do
					pcp+=" $1"
					shift
				done
				;;
			"--src")
				shift
				while [[ $# -gt 0 && "$1" != "--"* ]]; do
					src+=" $1"
					shift
				done
				;;
			"--dst")
				shift
				while [[ $# -gt 0 && "$1" != "--"* ]]; do
					dst+=" $1"
					shift
				done
				;;
			"--bw")
				shift
				bw="$1"
				shift
				;;
			"--"*|*)
				echo "Unknown option $1"
				print_usage
				exit 1
				;;
		esac
	done

	# Remove leading spaces
	smac="${smac:1}"
	dmac="${dmac:1}"
	vlan="${vlan:1}"
	pcp="${pcp:1}"
	src="${src:1}"
	dst="${dst:1}"

	if [[ "$dir" == "rx" ]] && [ -z "$smac" ] && [ -z "$dmac" ] && \
		[ -z "$vlan" ] && [ -z "$pcp" ] && [ -z "$src" ] && [ -z "$dst" ];
	then
		print_usage
		return $EINVAL
	fi


	echo "$dir" "$tc" > /sys/class/net/"$dev"/qos/add_tc
	if [ -n "$action" ]; then
		echo "$dir" "$action" > /sys/class/net/"$dev"/qos/add_tc_params/action
	fi
	if [[ "$dir" == "rx" ]]; then
		if [ -n "$smac" ]; then
			echo "$smac" > /sys/class/net/"$dev"/qos/add_tc_params/smac
		fi
		if [ -n "$dmac" ]; then
			echo "$dmac" > /sys/class/net/"$dev"/qos/add_tc_params/dmac
		fi
		if [ -n "$vlan" ]; then
			echo "$vlan" > /sys/class/net/"$dev"/qos/add_tc_params/vlan_id
		fi
		if [ -n "$pcp" ]; then
			echo "$pcp" > /sys/class/net/"$dev"/qos/add_tc_params/pcp
		fi
		if [ -n "$src" ]; then
			echo "$src" > /sys/class/net/"$dev"/qos/add_tc_params/src
		fi
		if [ -n "$dst" ]; then
			echo "$dst" > /sys/class/net/"$dev"/qos/add_tc_params/dst
		fi
	fi
	if [[ "$dir" == "tx" ]]; then
		if [ -n "$bw" ]; then
			echo "$bw" > /sys/class/net/"$dev"/qos/add_tc_params/bw
		fi
	fi
	echo "$dir" "done" > /sys/class/net/"$dev"/qos/add_tc
}

del_tc () {
	if [[ $# -lt 3 ]];
	then
		print_usage
		return $EINVAL
	fi

	local dev="$1"
	shift
	local dir="$1"
	shift
	local tc="$1"
	shift

	if [[ $# -gt 0 ]];
	then
		echo "Unexpected extra arguments"
		print_usage
		return $EINVAL
	fi

	echo "$dir" "$tc" > /sys/class/net/"$dev"/qos/del_tc
}

clear_table () {
	if [[ $# -lt 1 ]];
	then
		print_usage
		return $EINVAL
	fi

	local dev="$1"
	shift
	local cmd="clear"

	while [[ $# -gt 0 ]]; do
		case "$1" in
			"--pending")
				shift
				cmd+="-pending"
				;;
			"--"*|*)
				echo "Unknown option $1"
				print_usage
				exit 1
				;;
		esac
	done

	echo "$cmd" > /sys/class/net/"$dev"/qos/qos_table
}

show () {
	if [[ $# -lt 1 ]];
	then
		print_usage
		return $EINVAL
	fi

	local dev="$1"
	shift

	cat /sys/class/net/"$dev"/qos/qos_table
}

commit() {
	if [[ $# -lt 1 ]];
	then
		print_usage
		return $EINVAL
	fi

	local dev="$1"
	shift

	echo 1 > /sys/class/net/"$dev"/qos/commit
}

info() {
	if [[ $# -lt 1 ]];
	then
		print_usage
		return $EINVAL
	fi

	local dev="$1"
	shift

	cat /sys/class/net/"$dev"/qos/info
}

print_usage() {
	echo "
Usage:
	eth-qos <op> <dev> <rx|tx> <tc-id> [optional params]

	eth-qos add DEV DIR TC-ID --action <sw|hw> [TC-PARAMS]
	eth-qos del DEV DIR TC-ID
	eth-qos clear DEV [--pending]
	eth-qos show DEV
	eth-qos commit DEV
	eth-qos info DEV
	"
}

if [ "$1" == "add" ]
then
	shift
	add_tc $@
elif [ "$1" == "del" ]
then
	shift
	del_tc $@
elif [ "$1" == "clear" ]
then
	shift
	clear_table $@
elif [ "$1" == "show" ]
then
	shift
	show $@
elif [ "$1" == "commit" ]
then
	shift
	commit $@
elif [ "$1" == "info" ]
then
	shift
	info $@
else
	print_usage
fi