#!/bin/sh /etc/rc.common
#Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=79
STOP=97

start() {
	if [ -f /sys/module/dwmac_qcom_eth/parameters/qos_use_skprio ]; then
		echo 1 > /sys/module/dwmac_qcom_eth/parameters/qos_use_skprio
	fi
}

stop() {
	if [ -f /sys/module/dwmac_qcom_eth/parameters/qos_use_skprio ]; then
		echo 0 > /sys/module/dwmac_qcom_eth/parameters/qos_use_skprio
	fi
}
