BBFILES += "${LAYERDIR}/recipes/*/*.bb \
            ${LAYERDIR}/recipes/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-products/images/*.bbappend \
            ${LAYERDIR}/recipes-support/*/*.bbappend"

BBFILES:append:echo = " ${LAYERDIR}/rdkb/recipes-*/*/*.bb ${LAYERDIR}/rdkb/recipes-*/*/*.bbappend"
BBMASK:append:echo = " ^.*/linux-qcom-custom_.*\.bbappend$"
BBMASK:append:sa535m = " ^.*/linux-msm-src_.*\.bbappend$"

BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-data"
BBFILE_PRIORITY_qti-data = "12"
BBFILE_PATTERN_qti-data := "^${LAYERDIR}/"

LAYERSERIES_COMPAT_qti-data = "dunfell kirkstone scarthgap"
