#!/bin/sh
# Copyright (c) 2020, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of The Linux Foundation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# Ethernet Adaptation module
# init.d script to load Ethernet Adaptation module.

export MODULE_BASE=/usr/lib/modules/`uname -r`/
. $2

platform_v1=10000
platform_v2=20000
platform_v3=30000
sa515m=418
QCS405=352
sa2150p=452

if [ -f /sys/devices/soc0/soc_id ]; then
  soc_id=`cat /sys/devices/soc0/soc_id`
else
  soc_id=`cat /sys/devices/system/soc/soc0/id`
fi

if [ -f /sys/devices/soc0/hw_platform ]; then
  hw_platform=`cat /sys/devices/soc0/hw_platform`
else
  hw_platform=`cat /sys/devices/system/soc/soc0/hw_platform`
fi

if [ -f /sys/devices/soc0/platform_subtype_id ]; then
  platform_subtype_id=`cat /sys/devices/soc0/platform_subtype_id`
fi

if [ -f /sys/devices/soc0/platform_version ]; then
  platform_version=`cat /sys/devices/soc0/platform_version`
fi

platform_version_hex=`printf '%x\n' $platform_version`


eam_supported_targets () {

#for external AP uncomment below line of code
#current_target=EAP
#echo $current_target
#return 1

echo -n "Starting/Loading Ethernet Adaptation Module:entry " > /dev/kmsg
case "$soc_id" in
  "$sa515m")
    case "$hw_platform" in
      "ADP")
      case "$platform_subtype_id" in
        "5")
        case "$platform_version_hex" in
          "$platform_v1" | "$platform_v2" | "$platform_v3")
          echo -n "support for Ethernet Adaptation Module Enabled" > /dev/kmsg
          current_target=NAD
          echo $current_target
          return 1
        ;;
        esac
      ;;
      esac
    ;;
    esac
;;
esac

case "$soc_id" in
  "$sa2150p" | "$QCS405")
    case "$hw_platform" in
      "ADP")
      case "$platform_subtype_id" in
        "0")
        case "$platform_version_hex" in
          "$platform_v2" | "$platform_v3")
          echo -n "support for Ethernet Adaptation Module Enabled" > /dev/kmsg
          current_target=EAP
          echo $current_target
          return 1
        ;;
        esac
      ;;
      esac
    ;;
    esac
;;
esac
return 0
}

current_target=$(eam_supported_targets)
is_target_supported=$?

if [[ $is_target_supported -eq 1 ]]
then
  case "$1" in
    start)
    echo -n "Starting/Loading Ethernet Adaptation Module: " > /dev/kmsg
    echo "eth-adaption-layer:start/load" > /dev/kmsg
    case "$current_target" in
     "NAD")
       if [[ "$qip_type" == "IPv4" ]]
       then
         insmod $MODULE_BASE/extra/eth-adaption-layer.ko destipv4=$qremote_ip dest_port=$qremote_port server=0 iptype=0 vlan_intf=$qinterface.$qvlan_id connect_retry_cnt=15
       elif [[ "$qip_type" == "IPv6" ]]
       then
         insmod $MODULE_BASE/extra/eth-adaption-layer.ko destipv6=$qremote_ip dest_port=$qremote_port server=0 iptype=1 vlan_intf=$qinterface.$qvlan_id connect_retry_cnt=15
       fi
     ;;
     "EAP")
       if [[ "$qip_type" == "IPv4" ]]
       then
         insmod $MODULE_BASE/extra/eth-adaption-layer.ko destipv4=$qremote_ip dest_port=$qremote_port server=1 iptype=0 vlan_intf=$qinterface.$qvlan_id connect_retry_cnt=15
       elif [[ "$qip_type" == "IPv6" ]]
       then
         insmod $MODULE_BASE/extra/eth-adaption-layer.ko destipv6=$qremote_ip dest_port=$qremote_port server=1 iptype=1 vlan_intf=$qinterface.$qvlan_id connect_retry_cnt=15
       fi
     ;;
    esac
     echo "done loading Ethernet Adaptation Module"
  ;;
  stop)
    echo -n "Unloading Ethernet Adaptation Module "
    rmmod eth-adaption-layer.ko
    echo "done unloading Ethernet Adaptation Module"
  ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage { start | stop | restart}" >&2
    exit 1
  ;;
esac
else
  echo -n "No support for Ethernet Adaptation Module Enabled" > /dev/kmsg
fi

exit 0
