#!/bin/sh /etc/rc.common

#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=10
STOP=89

USE_PROCD=1
PROCD_DEBUG=1

start_service() {
	procd_open_instance
	procd_set_param command modprobe /lib/modules/rmnet_core.ko
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}

stop_service() {
	echo "Stopping datarmnet Instance"
}
