#!/bin/sh /etc/rc.common
#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear
# MKA-Supplicant start

USE_PROCD=1
PROCD_DEBUG=1

start_service() {
		procd_open_instance $1
		procd_set_param command /usr/sbin/mka_supplicant -D macsec_linux -i $1 -c /etc/mka_supplicant-$1.conf
		[ -x /sbin/ujail -a -e /etc/capabilities/macsec.json ] && {
			procd_add_jail macsec
			procd_set_param capabilities /etc/capabilities/macsec.json
			procd_set_param user macsec
			procd_set_param group macsec
		}
		procd_close_instance
}
