#! /bin/sh
# Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/lib/modules/`uname -r`/extra
set -e

case "$1" in
  start)
        echo -n "Starting/Loading dataipa modules: "
        echo "dataipa:start/load" > /dev/kmsg
        insmod $MODULE_BASE/gsim.ko > /dev/kmsg
        insmod $MODULE_BASE/ipam.ko > /dev/kmsg
        insmod $MODULE_BASE/ipanetm.ko > /dev/kmsg
        insmod $MODULE_BASE/rndisipam.ko > /dev/kmsg
        insmod $MODULE_BASE/ecmipam.ko > /dev/kmsg
        insmod $MODULE_BASE/ipa_clientsm.ko > /dev/kmsg
        echo "done loading dataipa core modules" > /dev/kmsg
        ;;
  stop)
        echo "Stopping dataipa modules" > /dev/kmsg
        echo -n "Bypassing Unloading of dataipa modules "
        ;;
  restart)
        echo "dataipa modules initiating restart" > /dev/kmsg
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
