#!/bin/sh

#Copyright (c) 2022-2024 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

/sbin/insmod /usr/lib/modules/gsim.ko
/sbin/insmod /usr/lib/modules/ecpri_dmam.ko
/sbin/insmod /usr/lib/modules/fpc_qsfp.ko

#Load PHY module with local oscillator as ref clock if Silabs initialization fails
if [ $(cat "/tmp/si5518_ready") == "1" ]; then
	/sbin/insmod /usr/lib/modules/lassen_qcom_aw_phy.ko
else
	/sbin/insmod /usr/lib/modules/lassen_qcom_aw_phy.ko qcom_aw_phy_ref_clk_mode=1
fi

/sbin/insmod /usr/lib/modules/lassen_mtip.ko
#/sbin/insmod /usr/lib/modules/lassen_macsec.ko
/sbin/insmod /usr/lib/modules/lassen_secure_eip.ko
/sbin/insmod /usr/lib/modules/ecpri_core.ko
/sbin/insmod /usr/lib/modules/ldmm.ko

