#!/bin/sh  /etc/rc.common
#
# Copyright (c) 2014, 2019-2021 The Linux Foundation. All rights reserved.
# Copyright (c) 2022-2025 Qualcomm Innovation Center, Inc. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# The shebang above has an extra space intentially to avoid having
# openwrt build scripts automatically enable this package starting
# at boot.

# START=26
# STOP=90

USE_PROCD=1

get_front_end_mode() {
	front_end=$(uci get ecm.global.acceleration_engine)
	#Default value is set to 'sfe'
	[ -n "$front_end" ] || front_end="sfe"

	case $front_end in
	auto)
		echo '0'
		;;
	sfe)
		echo '2'
		;;
	ipa)
		echo '7'
		;;
	sfe-ipa)
		echo '8'
		;;
	*)
		echo 'uci_option_acceleration_engine is invalid'
	esac
}

load_sfe() {

	[ -e "/lib/modules/qca-nss-sfe.ko" ] && {
		[ -d /sys/module/qca_nss_sfe ] || insmod /lib/modules/qca-nss-sfe.ko
	}

}

unload_sfe() {

	rmmod /lib/modules/qca-nss-sfe.ko

}

load_ecm() {

	[ -d /sys/module/ecm ] || {
		#ecm_dependency
		insmod /lib/modules/ecm.ko front_end_selection=$( get_front_end_mode )
	}

}

unload_ecm() {

	sysctl -w net.bridge.bridge-nf-call-ip6tables=0
	sysctl -w net.bridge.bridge-nf-call-iptables=0

	if [ -d /sys/module/ecm ]; then
		#
		# Stop ECM frontends
		#
		echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
		echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop

		#
		# Defunct the connections
		#
		echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
		sleep 5

		rmmod /lib/modules/ecm.ko
		sleep 1
	fi

}

pre_start() {
	#Pre-Start Commands

	sysctl -w net.bridge.bridge-nf-call-ip6tables=1
	sysctl -w net.bridge.bridge-nf-call-iptables=1

	#Disable ipa hw offload
	[ -f  /sys/class/net/eth0/suspend_ipa_offload ] && echo 1 > /sys/class/net/eth0/suspend_ipa_offload
	[ -f  /sys/class/net/eth1/suspend_ipa_offload ] && echo 1 > /sys/class/net/eth1/suspend_ipa_offload

	#Disable rx-vlan-offload to make sure NIC doesn't strip vlan tag.
	ethtool -K eth0 rx-vlan-offload off
	ethtool -K eth1 rx-vlan-offload off

	# Set conntrack event mode to 1 for 6.1 kernel to get the conntrack events from ECM
	echo 1 > /proc/sys/net/netfilter/nf_conntrack_events

}

post_start() {
	#Post-Start Commands

	# Delete original configuration before appending new
	sed '/net.bridge.bridge-nf-call-ip6tables/d' -i /etc/sysctl.d/qca-nss-ecm.conf
	sed '/net.bridge.bridge-nf-call-iptables/d' -i /etc/sysctl.d/qca-nss-ecm.conf

	echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.d/qca-nss-ecm.conf
	echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.d/qca-nss-ecm.conf

}

#start_service() {
start() {

	#Pre-Start commands
	pre_start

	#Load SFE
	load_sfe

	#Load ECM
	load_ecm

	#Post-Start commands
	post_start

}

#stop_service() {
stop() {

	# If ECM is already not loaded, just return.
	if [ ! -d /sys/module/ecm ]; then
		return
	fi

	sed '/net.bridge.bridge-nf-call-ip6tables=1/d' -i /etc/sysctl.d/qca-nss-ecm.conf
	sed '/net.bridge.bridge-nf-call-iptables=1/d' -i /etc/sysctl.d/qca-nss-ecm.conf

	#Stop/Disable ECM & SFE
	unload_ecm
	unload_sfe

	#Enable ipa hw offload as ECM is disabled/stopped
	[ -f  /sys/class/net/eth0/suspend_ipa_offload ] && echo 0 > /sys/class/net/eth0/suspend_ipa_offload
	[ -f  /sys/class/net/eth1/suspend_ipa_offload ] && echo 0 > /sys/class/net/eth1/suspend_ipa_offload

	#Enable rx-vlan-offload back as ECM is disabled.
	ethtool -K eth0 rx-vlan-offload on
	ethtool -K eth1 rx-vlan-offload on

}

# usage "etc/init.d/qca-nss-ecm start start
# usage "etc/init.d/qca-nss-ecm stop stop

case $1 in
	start)
		start
		;;

	stop)
		stop
		;;

	*)
		echo "wrong argument"
		;;

esac
