#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

# Create directory in /var/run/data location with required permissions
d /run/mka_supplicant 0755 macsec macsec - -
d /run/mka_authenticator 0755 macsec macsec - -

